name: AppLib

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
    - 'library/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'library/**'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Restore dependencies
      run: dotnet restore
      working-directory: library
    - name: Restore dependencies testing
      run: dotnet restore
      working-directory: library.testing
    - name: Build lib
      run: dotnet build library --no-restore
    - name: Build lib.test
      run: dotnet build library.testing --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal library.testing/library.testing.csproj
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: library.testing/*
  
  packandpublish:
    
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Determine version
      run: echo "VERSION=$(date +'%Y.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Create Package
      run: dotnet pack library --configuration Release -p:Version=$VERSION
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code-coverage-report
    - name: Upload
      run: dotnet nuget push library/bin/Release/math-sample.$VERSION.nupkg --skip-duplicate --api-key ${{secrets.GITHUB_TOKEN}} --source "github"
    
